# Multiple linear regression models
消費を目的変数として、所得、家族人数、年齢を説明変数とする重回帰分析を行う

Rの標準関数に加えて、`car` パッケージを使用します。

In [5]:
# 必要パッケージ
if (!require(car)) install.packages("car")
library(car)

Loading required package: car

Loading required package: carData

In [1]:
# CSVファイルの読み込み
data <- read.csv("../data/3-consumption.csv")

In [2]:
# データを確認（先頭5件）
head(data, 5)

  Number Y  X1 X2 X3
1 1      39 50 1  29
2 2      42 50 1  31
3 3      47 60 2  30
4 4      53 70 2  42
5 5      55 70 3  38

In [3]:
# 重回帰分析
model <- lm(Y ~ X1 + X2 + X3 , data = data)

In [4]:
# 結果の表示
summary(model)

Call:
lm(formula = Y ~ X1 + X2 + X3, data = data)

Residuals:
    Min      1Q  Median      3Q     Max
-4.0857 -1.5883 -0.7309  2.4422  3.4795

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  3.80205    3.91569   0.971   0.3460
X1           0.71196    0.04797  14.841 8.96e-11 ***
X2           2.28940    1.12846   2.029   0.0595 .
X3          -0.09388    0.10506  -0.894   0.3848
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.42 on 16 degrees of freedom
Multiple R-squared:  0.9811,	Adjusted R-squared:  0.9776
F-statistic: 277.1 on 3 and 16 DF,  p-value: 5.356e-14


$$
H_0:\ \beta_2 = \beta_3 = 0
$$

In [12]:
# Wald検定(F-statistic)
linearHypothesis(model, c("X2 = 0", "X3 = 0"), test = "F")

  Res.Df RSS       Df Sum of Sq F        Pr(>F)
1 18     119.46199 NA       NA        NA        NA
2 16      93.72757  2 25.73442  2.196529 0.1435823

In [13]:
# Wald検定(Chi-statistic)
linearHypothesis(model, c("X2 = 0", "X3 = 0"), test = "Chisq")

  Res.Df RSS       Df Sum of Sq Chisq    Pr(>Chisq)
1 18     119.46199 NA       NA        NA        NA
2 16      93.72757  2 25.73442  4.393058 0.1111884

$$
H_0:\ \beta_1 = 3\beta_2 + \beta_3
$$

In [15]:
# Wald検定(F-statistic)
linearHypothesis(model, "X1 = 3*X2 + X3", test = "F")

  Res.Df RSS       Df Sum of Sq F        Pr(>F)
1 17     112.84494 NA       NA        NA         NA
2 16      93.72757  1 19.11737  3.263478 0.08968211

In [16]:
# Wald検定(F-statistic)
linearHypothesis(model, "X1 = 3*X2 + X3", test = "Chisq")

  Res.Df RSS       Df Sum of Sq Chisq    Pr(>Chisq)
1 17     112.84494 NA       NA        NA         NA
2 16      93.72757  1 19.11737  3.263478 0.07083872